### PR TITLE
Miscellaneous fixes: fix wc behaviour, make cksum compile properly, fix return behaviour

### PR DESCRIPTION
**Pull request by moon-chilled**

### CODE REVIEW

**Comment by chaomodus** [comment]
Awesome stuff! I have merged a bit of a reorg to make things dub friendly, so this needs just some renames to be able to be merged.

**Comment by moon-chilled** [comment]
I can do that, yah, but can I ask: why make things friendly for dub?  I don't think anyone would want to use this as a package dependency, and it makes the build description file a *lot* longer and harder to wrangle.

**Comment by chaomodus** [comment]
I am informed that this is preferred by some d programmers. i don't care either way, i like the simplicity of meson, but dub is convenient also. It is tempting to make a shell script thatbuilds both the dub file and the meson file from a simpler description file since there are so many binaries in this.

**Comment by moon-chilled** [comment]
Personally, I think that the reasons people like dub don't really apply.  Dub is good because it manages dependencies, but no one is going to use this a dependency and I doubt (CMIIW) it's going to have major dependencies ever.  Dub also wasn't *designed* for this kind of thing; it wants to make one library or, possibly, one executable; not a bunch of executables.

Dub is good for a lot of things, and I use it for most of my projects just because it's easy, but I think for something like this it's not suitable.  I also have a libc; that uses makefiles instead of dub, because dub doesn't have the kind of granularity you need for a package.

**Comment by Member1221** [comment]
imho, it works fine as a dub package. For example, DCD uses dub as well.

I've set the dub file up to make each application a sub package, the main package pulling in each subpackage as a dependency thereby compiling all of them and putting them in an out/ folder.

As well, i'm currently working on a su & sudo implementation; as well a binding to shadow.h, which will be a seperate subpackage which could be useful elsewhere.

**Comment by moon-chilled** [comment]
Bindings to shadow.h are a good idea.  But making each program its own subpackage is IMO a huge hack.  It'll only get worse if we want to add common code for all the core utils; then each subpackage will have to depend on *another* subpackage, and the directory soup will get even more convoluted.

It just doesn't seem to me like it's worth the complexity of hacking this functionality into dub that it wasn't designed to facilitate.

**Comment by chaomodus** [comment]
I think in general the idea would be to have major functionality that is shared in separate packages.

I think the idea is that in these binary-oriented projects that dub is secondary to the more important meson build setup and should be eventually maintained unless it's being used to pull in dependencies.

We're in the process of separating the major components apart, for example the shadow stuff has been implemented in dunex-auth.

**Comment by chaomodus** [comment]
@moon-chilled I have fixed this to be able to merge with master (some minor conflicts). Is it okay if I merged this so we can start migrating this repository to dunex-core? thanks!

**Comment by moon-chilled** [comment]
Hi.  I'm really sorry, I didn't mean to leave this hanging like this!  I just spent the past 1.5w backpacking; meant to fix this up before I left, but wasn't able to get around to it in time.  Anyway: feel free to integrate.  I'm also spending tomorrow flying, but if you haven't done it by tomorrow night, I will fix it up then.

**Comment by moon-chilled** [comment]
@chaomodus should be mergeable now.  Sorry again for taking so long!

**Comment by chaomodus** [comment]
Hello hello, no worries about the timeframes! Obviously i haven't had a lot of time for this either. THanks for your efforts! Hope you had a good time backpacking :)

**Pull request merged**
